version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - simple-kafka-producer-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - simple-kafka-producer-net

  simple-kafka-producer:
    image: simple-kafka-producer
    depends_on:
      - kafka
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      KAFKA_CLIENT_ID: my-kafka
      KAFKA_BROKERS: kafka:29092
    ports:
      - 3000:3000
    networks:
      - simple-kafka-producer-net

networks:
  simple-kafka-producer-net:
    driver: bridge
