version: '3.4'

services:
  simple-kafka-producer:
    image: simple-kafka-producer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - .env
